#!/usr/bin/env bash

sghHookName=$(basename "${0}")

if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    sghBridge='./.git-hooks'
else
    sghBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${sghBridge}" ]; then
    . "${sghBridge}" || exit $?
else
    echo "Git hook bridge '${sghBridge}' not found."
fi

exit 0
