#!/usr/bin/env bash

cghHookName=$(basename "${0}")

if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    cghBridge='./.git-hooks'
else
    cghBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${cghBridge}" ]; then
    . "${cghBridge}" || exit $?
else
    echo "Git hook bridge '${cghBridge}' not found."
fi

exit 0
