#!/usr/bin/env bash
##
# This hook is called with the following parameters:
#   - $... It takes a variable number of parameters,
#          each of which is the name of ref that was actually updated.
#
# Standard input format:
#   NULL
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi

exit 0
