#!/usr/bin/env bash
##
# This hook is invoked by git am. It takes no parameter, and is invoked after
# the patch is applied and a commit is made.
#
# This hook is meant primarily for notification, and cannot affect the outcome
# of git am.
#
# This hook is called with the following parameters:
#   No parameters.
#
# Standard input format:
#   NULL
##

hasInput='false'
. "$(dirname $0)/_common"
