#!/usr/bin/env bash
##
# This hook is called with the following parameters:
#   No parameters.
#
# Standard input format:
#   - Old revision id.
#   - New revision id.
#   - Ref name
##

hasInput='true'
. "$(dirname $0)/_common"
