#!/usr/bin/env bash
##
# This hook is called with the following parameters:
#   No parameters.
#
# Standard input format:
#   - Old revision id.
#   - New revision id.
#   - Ref name
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi
