#!/usr/bin/env bash
##
# This hook is invoked by git merge, which happens when a git pull is done on a
# local repository. The hook takes a single parameter, a status flag specifying
# whether or not the merge being done was a squash merge.
# This hook cannot affect the outcome of git merge and is not executed,
# if the merge failed due to conflicts.
#
# This hook can be used in conjunction with a corresponding pre-commit hook to
# save and restore any form of metadata associated with the working tree
# (e.g.: permissions/ownership, ACLS, etc).
# See contrib/hooks/setgitperms.perl for an example of how to do this.
#
# This hook is called with the following parameters:
#   - $1 Flag specifying whether or not the merge being done was a squash merge.
#
# Standard input format:
#   NULL
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi

exit 0
