#!/usr/bin/env bash
##
# This hook is invoked when a git checkout is run after having updated the
# worktree. The hook is given three parameters.
# This hook cannot affect the outcome of git checkout.
#
# It is also run after git clone, unless the --no-checkout (-n) option is used.
# The first parameter given to the hook is the null-ref, the second the ref of
# the new HEAD and the flag is always 1.
#
# This hook can be used to perform repository validity checks, auto-display
# differences from the previous HEAD if different, or set working dir metadata
# properties.
#
# This hook is called with the following parameters:
#   - $1 The ref of the previous HEAD
#   - $2 The ref of the new HEAD
#   - $3 A flag indicating whether the checkout was a branch checkout
#        (changing branches, flag=1) or a file checkout
#        (retrieving a file from the index, flag=0)
#
# Standard input format:
#   NULL
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi
