#!/usr/bin/env bash
##
# The hook should exit with non-zero status after issuing an appropriate message
# if it wants to stop the commit.
#
# This hook is called with the following parameters:
#   It takes no parameter.
#
# Standard input format:
#   NULL
##

hasInput='false'
. "$(dirname $0)/_common"
