#!/usr/bin/env bash
##
# This hook is called with the following parameters:
#   If pushing without using a named remote those arguments will be equal.
#   - $1 Name of the remote to which the push is being done.
#   - $2 URL to which the push is being done.
#
# Standard input format:
#   Information about the commits which are being pushed is supplied as lines to
#   the standard input in the form:
#   - Local ref
#   - Local sha1
#   - Remote ref
#   - Remote sha1
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi
