#!/usr/bin/env bash
#
# Called by "git commit" with the name of the file that has the commit message,
# followed by the description of the commit message's source.
# The hook's purpose is to edit the commit message file.
# If the hook fails with a non-zero status, the commit is aborted.
#
# This hook is called with the following parameters:
#   - $1 The name of the file that has the commit message.
#   - $2 The description of the commit message's source.
#
# Standard input format:
#   NULL

hasInput='false'
. "$(dirname $0)/_common"
