#!/usr/bin/env bash
##
# This hook is called with the following parameters:
#   - $1 The hook receives the commit with which the tip of the current branch
#        is going to be updated.
#
# Standard input format:
#   NULL
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi

exit 0
