#!/usr/bin/env bash
##
# Called by "git receive-pack"
# A zero exit from the update hook allows the ref to be updated.
# Exiting with a non-zero status prevents git-receive-pack from updating that
# ref.
#
# This hook is called with the following parameters:
#   - $1 refname
#   - $2 sha1-old
#   - $3 sha1-new
##

hasInput='true'
if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi

exit 0
