#!/usr/bin/env bash

if [ "$(git rev-parse --is-bare-repository)" = 'true' ]; then
    gitHooksBridge='./.git-hooks'
else
    gitHooksBridge="$(git rev-parse --show-toplevel)/.git-hooks"
fi

if [ -s "${gitHooksBridge}" ]; then
    . "${gitHooksBridge}" || exit $?
fi

exit 0
